cart_put:
  path: /cart/{id}
  controller: Granah\Apps\CartShop\Backend\Controller\Cart\CartPutController
  methods: [PUT]

cart_delete:
  path: /cart/{id}
  controller: Granah\Apps\CartShop\Backend\Controller\Cart\CartDeleteController
  methods: [DELETE]

cart_GET:
  path: /cart/{id}
  controller: Granah\Apps\CartShop\Backend\Controller\Cart\CartGetController
  methods: [ GET ]

cart_put_confirm:
  path: /cart/{id}/confirm
  controller: Granah\Apps\CartShop\Backend\Controller\Cart\CartPutConfirmController
  methods: [PUT]
