cart_put:
  path: /cart/{id}
  controller: Granah\Apps\CartShop\Backend\Controller\Cart\CartPutController
  methods: [PUT]

cart_delete:
  path: /cart/{id}
  controller: Granah\Apps\CartShop\Backend\Controller\Cart\CartDeleteController
  methods: [DELETE]
